name: OpenPlane

options:
  bundleIdPrefix: com.openplane
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: ""

targets:
  OpenPlane:
    type: application
    platform: iOS
    sources:
      - path: OpenPlane
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.openplane.OpenPlane
        INFOPLIST_FILE: OpenPlane/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
