name: PlaneMobile

options:
  bundleIdPrefix: com.openplane
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: ""

targets:
  PlaneMobile:
    type: application
    platform: iOS
    sources:
      - path: PlaneMobile
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.openplane.PlaneMobile
        INFOPLIST_FILE: PlaneMobile/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

